-- TravelTech Hub - single-category seed data: Travel Tech Marketing
--
-- Generated by scripts/generate-category-seed.mjs from src/config/categories.js
-- and src/data/travel-tech-marketing.json. Do not hand-edit - rerun
-- `node scripts/generate-category-seed.mjs travel-tech-marketing` instead.
--
-- Unlike supabase/seed.sql (which re-upserts every category, listing, news
-- and event row), this file touches ONLY the "Travel Tech Marketing" category row
-- and its listings, so it's safe to run against a production database that
-- already has the full seed.sql applied without re-touching anything else.
--
-- Run this against a project that already has 001_initial_schema.sql
-- applied, using a role that bypasses RLS (the Supabase SQL Editor and
-- `supabase db push` both connect as the "postgres" role, which does).
--
-- Idempotent: the category is upserted on its primary key, and each listing
-- is upserted on its unique (legacy_id, category_id) pair, with child rows
-- (features/usps/products/target markets) deleted and reinserted in the same
-- statement - safe to rerun.
--
-- Data-quality note: the source JSON explicitly disclaims that email and
-- phone values are plausible placeholder-format examples, not verified
-- contact details (see the "_comment" field in src/data/travel-tech-marketing.json).
-- Every seeded listing therefore gets email = null, phone = null, and
-- contact_verified = false regardless of what the source JSON contained.
--
-- Category: Travel Tech Marketing   Listings: 20

begin;

insert into public.categories (id, name, short_name, route, description, color, icon, display_order, is_active)
values
  ('travel-tech-marketing', 'Travel Tech Marketing', 'Marketing', '/travel-tech-marketing', 'Digital marketing agencies, ad-tech and media platforms specialised in reaching travelers on behalf of hotels, destinations and travel brands.', 'zinc', 'Megaphone', 20, true)
on conflict (id) do update set
  name = excluded.name,
  short_name = excluded.short_name,
  route = excluded.route,
  description = excluded.description,
  color = excluded.color,
  icon = excluded.icon,
  display_order = excluded.display_order,
  is_active = excluded.is_active;

do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'sojern', null, 'travel-tech-marketing', 'Sojern', 'sojern',
    'SJ', 'Sojern is a San Francisco-based travel marketing platform that uses traveler intent data to run programmatic advertising, email and metasearch campaigns for airlines, hotels, DMOs and attractions. Its Traveler Platform helps travel brands identify and retarget in-market travelers across channels.',
    'Enterprise/Custom', '$$', null, null,
    'https://www.sojern.com', 'San Francisco, United States', 2012,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Traveler intent data platform', 0),
    (v_listing_id, 'Programmatic display & video ads', 1),
    (v_listing_id, 'Metasearch campaign management', 2),
    (v_listing_id, 'Email marketing automation', 3),
    (v_listing_id, 'Attribution & multi-touch reporting', 4),
    (v_listing_id, 'DMO co-op marketing tools', 5);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Large proprietary traveler intent dataset', 0),
    (v_listing_id, 'Full-funnel campaign management', 1),
    (v_listing_id, 'Deep airline & hospitality client base', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Sojern Traveler Platform', 0),
    (v_listing_id, 'Sojern Email Marketing', 1),
    (v_listing_id, 'Sojern Metasearch', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'Global'),
    (v_listing_id, 'North America'),
    (v_listing_id, 'Europe'),
    (v_listing_id, 'Asia Pacific');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'adara', null, 'travel-tech-marketing', 'Adara', 'adara',
    'AD', 'Adara is a travel data and marketing company that pools first-party data from airlines, hotels and travel intermediaries into a cooperative data platform, letting travel brands target and measure advertising against verified traveler audiences rather than modeled ones.',
    'Enterprise/Custom', '$$$', null, null,
    'https://www.adara.com', 'San Francisco, United States', 2009,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Cooperative traveler data pool', 0),
    (v_listing_id, 'Audience targeting & lookalikes', 1),
    (v_listing_id, 'Cross-channel campaign measurement', 2),
    (v_listing_id, 'Fraud-resistant identity resolution', 3),
    (v_listing_id, 'Real-time bidding integrations', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'First-party data cooperative model', 0),
    (v_listing_id, 'Trusted by major global airlines', 1),
    (v_listing_id, 'Privacy-conscious data partnerships', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Adara Impact', 0),
    (v_listing_id, 'Adara Audiences', 1),
    (v_listing_id, 'Adara Analytics', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'Global'),
    (v_listing_id, 'North America'),
    (v_listing_id, 'Europe');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'mmgy-global', null, 'travel-tech-marketing', 'MMGY Global', 'mmgy-global',
    'MG', 'MMGY Global is a full-service travel and tourism marketing agency offering strategy, creative, media buying and public relations for destinations, hotel brands and travel associations, backed by its own traveler research arm, MMGY Travel Intelligence.',
    'Enterprise/Custom', '$$$', null, null,
    'https://www.mmgyglobal.com', 'Kansas City, United States', 1975,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Integrated advertising campaigns', 0),
    (v_listing_id, 'Destination brand strategy', 1),
    (v_listing_id, 'Travel PR & public affairs', 2),
    (v_listing_id, 'Traveler research & insights', 3),
    (v_listing_id, 'Media planning & buying', 4),
    (v_listing_id, 'Social & content marketing', 5);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Decades of destination marketing pedigree', 0),
    (v_listing_id, 'In-house traveler research division', 1),
    (v_listing_id, 'Long-standing DMO relationships', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'MMGY Brand Strategy', 0),
    (v_listing_id, 'MMGY Media', 1),
    (v_listing_id, 'MMGY Travel Intelligence', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'North America'),
    (v_listing_id, 'Global');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'miles-partnership', null, 'travel-tech-marketing', 'Miles Partnership', 'miles-partnership',
    'MP', 'Miles Partnership is a destination marketing agency working with tourism boards, DMOs and hospitality brands on website design, digital advertising, content and industry partnership programs that drive visitation and direct bookings.',
    'Enterprise/Custom', '$$', null, null,
    'https://www.milespartnership.com', 'Sarasota, United States', 1988,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Destination website design', 0),
    (v_listing_id, 'Digital advertising campaigns', 1),
    (v_listing_id, 'Content & storytelling programs', 2),
    (v_listing_id, 'Partner co-op marketing platforms', 3),
    (v_listing_id, 'Visitor guide publishing', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Deep destination marketing specialization', 0),
    (v_listing_id, 'Long-running tourism board partnerships', 1),
    (v_listing_id, 'Combines content, tech and media in-house', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Miles Digital', 0),
    (v_listing_id, 'Miles Content', 1),
    (v_listing_id, 'Miles Partner Marketing', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'North America');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'simpleview', null, 'travel-tech-marketing', 'Simpleview', 'simpleview',
    'SV', 'Simpleview provides a CRM and digital marketing platform built specifically for destination marketing organizations, combining website CMS, partner/member management, email marketing and analytics in one system used by hundreds of DMOs worldwide.',
    'Subscription', '$$', null, null,
    'https://www.simpleviewinc.com', 'Tucson, United States', 1991,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'DMO-specific CMS & website platform', 0),
    (v_listing_id, 'Partner & member CRM', 1),
    (v_listing_id, 'Email marketing automation', 2),
    (v_listing_id, 'Visitor analytics dashboards', 3),
    (v_listing_id, 'Digital asset management', 4),
    (v_listing_id, 'Group & meeting sales tools', 5);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Purpose-built for DMOs, not generic marketing', 0),
    (v_listing_id, 'Large installed base of tourism boards', 1),
    (v_listing_id, 'All-in-one CRM plus CMS platform', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Simpleview CRM', 0),
    (v_listing_id, 'Simpleview CMS', 1),
    (v_listing_id, 'Simpleview Media', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'North America'),
    (v_listing_id, 'Global');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'tambourine', null, 'travel-tech-marketing', 'Tambourine', 'tambourine',
    'TB', 'Tambourine is a hospitality digital marketing agency serving independent hotels and resorts with website design, SEO, paid media and direct-booking conversion strategy aimed at reducing OTA dependency.',
    'Subscription', '$$', null, null,
    'https://www.tambourine.com', 'Fort Lauderdale, United States', 1993,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Hotel website design & CRO', 0),
    (v_listing_id, 'SEO & paid search management', 1),
    (v_listing_id, 'Direct booking strategy', 2),
    (v_listing_id, 'Social media management', 3),
    (v_listing_id, 'Email marketing campaigns', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Focused exclusively on independent hotels', 0),
    (v_listing_id, 'Strong direct-booking conversion track record', 1),
    (v_listing_id, 'Boutique, hands-on account teams', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Tambourine Websites', 0),
    (v_listing_id, 'Tambourine Media', 1),
    (v_listing_id, 'Tambourine SEO', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'North America'),
    (v_listing_id, 'Latin America');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'vizergy', null, 'travel-tech-marketing', 'Vizergy', 'vizergy-2',
    'VZ', 'Vizergy delivers digital marketing and website services for hotels and resorts, including responsive website design, search marketing and a proprietary revenue-focused reporting suite that ties marketing spend to booking outcomes.',
    'Subscription', '$$', null, null,
    'https://www.vizergy.com', 'Jacksonville, United States', 1995,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Responsive hotel website design', 0),
    (v_listing_id, 'Paid search & display advertising', 1),
    (v_listing_id, 'Revenue-focused marketing reporting', 2),
    (v_listing_id, 'Email & CRM marketing', 3),
    (v_listing_id, 'Local SEO management', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Marketing tied directly to revenue reporting', 0),
    (v_listing_id, 'Long track record with independent hotels', 1),
    (v_listing_id, 'Combines design and media under one roof', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Vizergy Websites', 0),
    (v_listing_id, 'Vizergy Digital Marketing', 1),
    (v_listing_id, 'Vizergy Analytics', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'North America');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'blue-magnet-interactive', null, 'travel-tech-marketing', 'Blue Magnet Interactive', 'blue-magnet-interactive',
    'BM', 'Blue Magnet Interactive is a hospitality-focused digital marketing agency offering website development, SEO, paid media and social advertising for independent hotels, resorts and hotel management groups.',
    'Subscription', '$', null, null,
    'https://www.bluemagnetinteractive.com', 'Fort Worth, United States', 1999,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Hotel website development', 0),
    (v_listing_id, 'SEO & content marketing', 1),
    (v_listing_id, 'Paid social & display campaigns', 2),
    (v_listing_id, 'Conversion rate optimization', 3),
    (v_listing_id, 'Reputation management', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Boutique agency with senior-led accounts', 0),
    (v_listing_id, 'Hospitality-only client focus', 1),
    (v_listing_id, 'Transparent performance reporting', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Blue Magnet Websites', 0),
    (v_listing_id, 'Blue Magnet SEO', 1),
    (v_listing_id, 'Blue Magnet Paid Media', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'North America');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'milestone-inc', null, 'travel-tech-marketing', 'Milestone Inc', 'milestone-inc-2',
    'MS', 'Milestone is a hospitality digital marketing company providing website design, SEO, paid media and its proprietary MOJO marketing intelligence platform that gives hoteliers visibility into competitive digital marketing performance.',
    'Subscription', '$$', null, null,
    'https://www.milestoneinternet.com', 'Bend, United States', 1992,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Hotel website & CRO services', 0),
    (v_listing_id, 'SEO & paid search', 1),
    (v_listing_id, 'Competitive marketing intelligence (MOJO)', 2),
    (v_listing_id, 'Social media marketing', 3),
    (v_listing_id, 'Email marketing campaigns', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Proprietary competitive intelligence tool', 0),
    (v_listing_id, 'Data-driven campaign optimization', 1),
    (v_listing_id, 'Established hospitality agency network', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Milestone Websites', 0),
    (v_listing_id, 'MOJO Minder', 1),
    (v_listing_id, 'Milestone Digital Marketing', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'North America');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'nextguest', null, 'travel-tech-marketing', 'NextGuest', 'nextguest',
    'NG', 'NextGuest is a full-service hotel digital marketing agency offering media buying, SEO, website design and creative services for independent hotels, resorts and hospitality management companies, with a focus on measurable direct-revenue impact.',
    'Subscription', '$$', null, null,
    'https://www.nextguest.com', 'New York, United States', 2013,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Full-funnel paid media management', 0),
    (v_listing_id, 'Hotel website design', 1),
    (v_listing_id, 'SEO & content strategy', 2),
    (v_listing_id, 'Creative & brand campaigns', 3),
    (v_listing_id, 'Performance & revenue reporting', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Media-buying scale across major hotel groups', 0),
    (v_listing_id, 'In-house creative studio', 1),
    (v_listing_id, 'Revenue-attributed campaign reporting', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'NextGuest Media', 0),
    (v_listing_id, 'NextGuest Websites', 1),
    (v_listing_id, 'NextGuest Creative', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'North America'),
    (v_listing_id, 'Global');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'hebs-digital', null, 'travel-tech-marketing', 'HeBS Digital', 'hebs-digital',
    'HD', 'HeBS Digital is a hospitality e-commerce and digital marketing agency offering website design, SEO, paid media and its Smart Data platform, focused on maximizing direct bookings for hotels and hotel groups.',
    'Subscription', '$$', null, null,
    'https://www.hebsdigital.com', 'New York, United States', 2001,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Hotel e-commerce website platform', 0),
    (v_listing_id, 'SEO & paid media management', 1),
    (v_listing_id, 'Smart Data guest intelligence', 2),
    (v_listing_id, 'Conversion rate optimization', 3),
    (v_listing_id, 'Email & remarketing campaigns', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Long-established direct-booking specialist', 0),
    (v_listing_id, 'Proprietary guest intelligence data platform', 1),
    (v_listing_id, 'Enterprise hotel group experience', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'HeBS Digital Websites', 0),
    (v_listing_id, 'Smart Data Platform', 1),
    (v_listing_id, 'HeBS Digital Media', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'North America'),
    (v_listing_id, 'Global');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'fuel-travel', null, 'travel-tech-marketing', 'Fuel Travel', 'fuel-travel',
    'FT', 'Fuel Travel is a digital marketing agency serving independent hotels with mobile-first website design, paid search, SEO and social media management, aimed at boosting direct bookings for small and mid-size properties.',
    'Subscription', '$', null, null,
    'https://www.fueltravel.com', 'Wichita, United States', 2010,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Mobile-first website design', 0),
    (v_listing_id, 'Paid search & social advertising', 1),
    (v_listing_id, 'SEO management', 2),
    (v_listing_id, 'Social media content management', 3),
    (v_listing_id, 'Booking conversion optimization', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Affordable option for independent hotels', 0),
    (v_listing_id, 'Mobile-first design philosophy', 1),
    (v_listing_id, 'Hands-on account management', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Fuel Websites', 0),
    (v_listing_id, 'Fuel Paid Media', 1),
    (v_listing_id, 'Fuel Social', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'North America');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'screen-pilot', null, 'travel-tech-marketing', 'Screen Pilot', 'screen-pilot',
    'SP', 'Screen Pilot is a hospitality digital marketing agency specializing in paid search, SEO and analytics for hotels and resorts, known for transparent, data-driven reporting tied directly to booking revenue.',
    'Subscription', '$$', null, null,
    'https://www.screenpilot.com', 'Denver, United States', 2005,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Paid search campaign management', 0),
    (v_listing_id, 'SEO & organic visibility', 1),
    (v_listing_id, 'Custom analytics dashboards', 2),
    (v_listing_id, 'Website conversion audits', 3),
    (v_listing_id, 'Metasearch bid management', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Analytics-first agency culture', 0),
    (v_listing_id, 'Transparent revenue-tied reporting', 1),
    (v_listing_id, 'Boutique, senior-staffed accounts', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Screen Pilot Paid Search', 0),
    (v_listing_id, 'Screen Pilot SEO', 1),
    (v_listing_id, 'Screen Pilot Analytics', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'North America');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'the-hotels-network', null, 'travel-tech-marketing', 'The Hotels Network', 'the-hotels-network',
    'THN', 'The Hotels Network is a Barcelona-based conversion and personalization platform that helps hotels increase direct bookings through website personalization, price comparison widgets, retargeting and booking-abandonment recovery tools.',
    'Commission', '$$', null, null,
    'https://www.thehotelsnetwork.com', 'Barcelona, Spain', 2015,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Website personalization engine', 0),
    (v_listing_id, 'Price comparison & parity widgets', 1),
    (v_listing_id, 'Booking abandonment recovery', 2),
    (v_listing_id, 'A/B testing tools', 3),
    (v_listing_id, 'Direct-booking retargeting', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Personalization-first approach to conversion', 0),
    (v_listing_id, 'Widely adopted price-comparison widget', 1),
    (v_listing_id, 'Strong presence with European hotel groups', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Booster', 0),
    (v_listing_id, 'Metasearch Manager', 1),
    (v_listing_id, 'Smart Pixel', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'Europe'),
    (v_listing_id, 'Global'),
    (v_listing_id, 'Latin America');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'digital-alchemy', null, 'travel-tech-marketing', 'Digital Alchemy', 'digital-alchemy',
    'DA', 'Digital Alchemy provides automated guest marketing and email campaign software for hotels, combining trigger-based messaging with creative services to help hotel marketing teams run always-on lifecycle campaigns.',
    'Subscription', '$$', null, null,
    'https://www.digitalalchemy.io', 'Dallas, United States', 2013,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Automated lifecycle email campaigns', 0),
    (v_listing_id, 'Trigger-based guest messaging', 1),
    (v_listing_id, 'Campaign creative services', 2),
    (v_listing_id, 'Segmentation & personalization', 3),
    (v_listing_id, 'Performance reporting dashboards', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Always-on automated campaign library', 0),
    (v_listing_id, 'Combines software with creative services', 1),
    (v_listing_id, 'Deep hotel group implementation experience', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Digital Alchemy Email', 0),
    (v_listing_id, 'Digital Alchemy Creative Studio', 1);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'North America'),
    (v_listing_id, 'Global');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'expedia-group-media-solutions', null, 'travel-tech-marketing', 'Expedia Group Media Solutions', 'expedia-group-media-solutions',
    'EGM', 'Expedia Group Media Solutions is the advertising arm of Expedia Group, letting hotels, airlines, tourism boards and travel brands run sponsored placements and display campaigns across Expedia''s network of travel booking sites to reach in-market travelers.',
    'Per Booking', '$$$', null, null,
    'https://advertising.expediagroup.com', 'Seattle, United States', 1996,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Sponsored placement advertising', 0),
    (v_listing_id, 'Cross-brand display campaigns', 1),
    (v_listing_id, 'Audience targeting on booking intent', 2),
    (v_listing_id, 'Co-op marketing programs', 3),
    (v_listing_id, 'Campaign performance reporting', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Access to Expedia Group''s traveler audience', 0),
    (v_listing_id, 'Advertising placed at point of booking intent', 1),
    (v_listing_id, 'Cross-brand reach across Expedia''s travel sites', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Sponsored Listings', 0),
    (v_listing_id, 'Expedia Display Ads', 1),
    (v_listing_id, 'Destination Marketing Program', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'Global');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'tripadvisor-business-advantage', null, 'travel-tech-marketing', 'TripAdvisor Business Advantage', 'tripadvisor-business-advantage',
    'TA', 'TripAdvisor Business Advantage is TripAdvisor''s advertising and profile-enhancement program for hotels and attractions, offering sponsored placements, business listing tools and analytics to help properties stand out to travelers researching on TripAdvisor.',
    'Subscription', '$$', null, null,
    'https://www.tripadvisor.com/Owners', 'Needham, United States', 2000,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Sponsored placement advertising', 0),
    (v_listing_id, 'Enhanced business listing tools', 1),
    (v_listing_id, 'Competitor comparison removal', 2),
    (v_listing_id, 'Review management dashboard', 3),
    (v_listing_id, 'Traveler engagement analytics', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Direct access to TripAdvisor''s review audience', 0),
    (v_listing_id, 'Placement at the review-research moment', 1),
    (v_listing_id, 'Widely recognized traveler-trust brand', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Business Advantage', 0),
    (v_listing_id, 'Sponsored Placements', 1),
    (v_listing_id, 'TripAdvisor Analytics', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'Global');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'amadeus-media-solutions', null, 'travel-tech-marketing', 'Amadeus Media Solutions', 'amadeus-media-solutions',
    'AMS', 'Amadeus Media Solutions lets airlines and travel sellers monetize and target advertising within Amadeus''s global distribution and shopping systems, connecting brands with travel agents and travelers during the booking search process.',
    'Enterprise/Custom', '$$$', null, null,
    'https://amadeus.com/en/industries/media-solutions', 'Madrid, Spain', 1987,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'In-GDS advertising placements', 0),
    (v_listing_id, 'Travel agent audience targeting', 1),
    (v_listing_id, 'Airline ancillary media programs', 2),
    (v_listing_id, 'Shopping-moment sponsored content', 3),
    (v_listing_id, 'Campaign analytics & reporting', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Reaches travel agents at point of sale', 0),
    (v_listing_id, 'Backed by Amadeus''s global distribution scale', 1),
    (v_listing_id, 'Deep integration with airline shopping systems', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Amadeus Media Exchange', 0),
    (v_listing_id, 'Amadeus Advertising', 1),
    (v_listing_id, 'Amadeus Sponsored Content', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'Global'),
    (v_listing_id, 'Europe'),
    (v_listing_id, 'Asia Pacific');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'criteo-for-travel', null, 'travel-tech-marketing', 'Criteo for Travel', 'criteo-for-travel',
    'CR', 'Criteo for Travel applies Criteo''s commerce media and retargeting technology to the travel vertical, helping airlines, hotels and OTAs re-engage site visitors and drive incremental bookings through personalized dynamic ads.',
    'Per Booking', '$$', null, null,
    'https://www.criteo.com', 'Paris, France', 2005,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Dynamic retargeting ads', 0),
    (v_listing_id, 'Cross-device audience matching', 1),
    (v_listing_id, 'Commerce media marketplace', 2),
    (v_listing_id, 'Lookalike audience targeting', 3),
    (v_listing_id, 'Real-time bid optimization', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Large-scale commerce media network', 0),
    (v_listing_id, 'Strong dynamic creative retargeting engine', 1),
    (v_listing_id, 'Cross-device identity resolution at scale', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'Criteo Retargeting', 0),
    (v_listing_id, 'Criteo Commerce Growth', 1),
    (v_listing_id, 'Criteo Audience Match', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'Global'),
    (v_listing_id, 'Europe'),
    (v_listing_id, 'North America');

end $seed_listing$;


do $seed_listing$
declare
  v_listing_id uuid;
begin
  insert into public.listings (
    legacy_id, owner_id, category_id, name, slug, logo_initials, description,
    pricing_model, price_range, email, phone, website, headquarters, founded,
    status, featured, verified, contact_verified, submitted_at, approved_at
  ) values (
    'trivago-business-studio', null, 'travel-tech-marketing', 'Trivago Business Studio', 'trivago-business-studio',
    'TBS', 'Trivago Business Studio is trivago''s marketing and analytics suite for hotel advertisers, giving hoteliers tools to manage their metasearch presence, bidding strategy and performance reporting directly on the trivago platform.',
    'Per Booking', '$$', null, null,
    'https://business.trivago.com', 'Düsseldorf, Germany', 2005,
    'approved', false, false, false, now(), now()
  )
  on conflict (legacy_id, category_id) do update set
    category_id = excluded.category_id,
    name = excluded.name,
    slug = excluded.slug,
    logo_initials = excluded.logo_initials,
    description = excluded.description,
    pricing_model = excluded.pricing_model,
    price_range = excluded.price_range,
    email = excluded.email,
    phone = excluded.phone,
    website = excluded.website,
    headquarters = excluded.headquarters,
    founded = excluded.founded,
    status = excluded.status,
    contact_verified = excluded.contact_verified
  returning id into v_listing_id;

  delete from public.listing_features where listing_id = v_listing_id;
  insert into public.listing_features (listing_id, value, display_order) values
    (v_listing_id, 'Metasearch bid management', 0),
    (v_listing_id, 'Hotel profile & content management', 1),
    (v_listing_id, 'Performance analytics dashboard', 2),
    (v_listing_id, 'Rate parity monitoring', 3),
    (v_listing_id, 'Audience insights reporting', 4);

  delete from public.listing_usps where listing_id = v_listing_id;
  insert into public.listing_usps (listing_id, value, display_order) values
    (v_listing_id, 'Direct access to trivago''s metasearch traffic', 0),
    (v_listing_id, 'Native bidding tools built for the platform', 1),
    (v_listing_id, 'Large European hotel advertiser base', 2);

  delete from public.listing_products where listing_id = v_listing_id;
  insert into public.listing_products (listing_id, value, display_order) values
    (v_listing_id, 'trivago Business Studio', 0),
    (v_listing_id, 'trivago Hotel Manager', 1),
    (v_listing_id, 'trivago Insights', 2);

  delete from public.listing_target_markets where listing_id = v_listing_id;
  insert into public.listing_target_markets (listing_id, value) values
    (v_listing_id, 'Europe'),
    (v_listing_id, 'Global');

end $seed_listing$;

commit;
